### ISSUE TITLE
quantisation implementation

### ISSUE THREAD

**Issue by huyphan168** [SqueezeAILab/SqueezeLLM#12]
Hi, I want to say thank you by your great work on quantisation. However, in the current codebase, I don't see any specific implementation on how these quantisation algorithms work? Can you provide them in the near future?

**Comment by ArEnSc** [comment]
@kssteven418 for visibility

**Comment by JasonOSX** [comment]
I also cannot wait for this to come available! Could be a gamechanger (at least until something better comes along)

**Comment by hudengjunai** [comment]
Hi, could you please release the quantization code? I want to quant a model for deploy

**Comment by chouxianyu** [comment]
@kssteven418 
I'd appreciate it if you could release the implementation code for weight quantization.

**Comment by siddharth28392** [comment]
Can you provide code for quantization? I want to quant a finetuned model for deploy

**Comment by ArEnSc** [comment]
This technique may be irrelvant now that we have Quip and people are porting that now

**Comment by siddharth28392** [comment]
Can you share link to github repository for Quip ?

**Comment by ArEnSc** [comment]
https://github.com/PanQiWei/AutoGPTQ/issues/228#issuecomment-1666464177

**Comment by kssteven418** [comment]
thanks for your patience. We have released our quantization code
