### ISSUE TITLE
How to save the quantized model with full weights?

### ISSUE THREAD

**Issue by ChrisHayduk** [SqueezeAILab/SqueezeLLM#22]
After quantizing the model, I'd like to be able to save the resulting model for later use. However, PyTorch's save commands do not seem to be working properly. Is there anything I need to change in the model config?

**Comment by abacaj** [comment]
Came to ask the same thing. Any reference code to quantize and save the models?

**Comment by kssteven418** [comment]
thanks for your patience. we have just released the code that quantizes and saves the models
