### ISSUE TITLE
Vicuna v1.3

### ISSUE THREAD

**Issue by nestordemeure** [SqueezeAILab/SqueezeLLM#30]
Great work, thank you for sharing it!

I was waiting for the Vicuna v1.3 weights to get out (they were previously marked as *coming soon* in the readme) as it is my current model of choice (and perform significantly better than v1.1) but I see that this section has been removed from the readme.

Is there any plan to quantize that family of models?

**Comment by kssteven418** [comment]
We are currently running internal evaluations before we release the models, so it shouldn't take that long!
