### ISSUE TITLE
Will It work in V100 GPU ?

### ISSUE THREAD

**Issue by Sravanth-k27** [SqueezeAILab/SqueezeLLM#4]

**Comment by leocnj** [comment]
Do you mind sharing your finding? Yes or No. I tend to vote for No given experiences on other related technologies, like AWQ.

**Comment by kssteven418** [comment]
We have tested it on V100, and it worked fine. You can also test it out on the [vLLM ](https://github.com/vllm-project/vllm) framework.

**Comment by leocnj** [comment]
Thanks. In vLLM, when using AWQ, it requires a GPU >= 7.5 score. This rules out using V100 with a 7.0 score. Good to know that squeezeLM, the other 4-bit model supported by it, can work on V100.
