### ISSUE TITLE
Add 65B-q3 evaluation

### ISSUE THREAD

**Issue by ingenieroariel** [SqueezeAILab/SqueezeLLM#5]
Hello, thanks for this paper!

When looking at the curve that suggests 30B-q3 could be used instead of 7B fp16 I got really interested in seeing the graphic with 65B-q3. You mention using A600 GPUs which have 48GB. Would a llama 65b q3 theoretically fit there?

My reference is llama.cpp q5_1 being 46GB.

Thanks in advance!

**Comment by kssteven418** [comment]
Hi, we are working on the 65B model now, and we are also planning to open-source it.
The exact memory requirement will only be available after proper profiling, but given that our quantization scheme does not exhibit a huge difference in terms of memory consumption as compared to the previous schemes, we do think it will theoretically fit into 48GB.
