### ISSUE TITLE
access to quantisation code

### ISSUE THREAD

**Issue by ri938** [SqueezeAILab/SqueezeLLM#7]
Do you intend to release the code for creating the quantisation weights?

I would like to port this to GPTJ model (which is open source unlike llama).  But to do this I would need to code for computing the quantised weights. It seems only the inference code is released so far.

**Comment by ArEnSc** [comment]
I am pretty sure all that has to be done is you just need to apply this to the layers  make_quant_lut(model, layers, wbits)
then save it, I think that's about it ... I can probably do it sometime next week

**Comment by kssteven418** [comment]
Thanks for your patience. We have released the quantization code.
